/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function axumVersion(): string
export class AxumApp {
  constructor()
  get(path: string, cb: (request: AxumRequest, response: AxumResponse) => void): void
  listen(port: number): Promise<void>
}
export class AxumRequest {
  body(): Record<string, any>
}
export class AxumResponseInternal { }
export class AxumResponse {
  sendJson(body: any): this
  status(status: number): this
  setHeader(key: string, value: string): this
}
