/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function axumVersion(): string
export class AxumApp {
  constructor()
  get(path: string): void
  listen(port: number): Promise<void>
}
